Type: "AWS::Lambda::Function"
Properties:
  FunctionName: "delete-one-materials-painters"
  Handler: index.handler
  Runtime: nodejs12.x
  Role:
    Ref: LambdaRoleARN
  Timeout: 300
  Code:
    S3Bucket:
      Ref: BucketS3
    S3Key: "materials/delete-one-materials-painters/delete-one-materials-painters.zip"
