service: painters
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

plugins:
  - serverless-offline

functions:
  budget-painters:
    role: "arn:aws:iam::178233312549:role/LabRole"
    handler: src/budget_lambda/budget-painters.handler
    events:
      - httpApi:
          path: /budget
          method: post
  get-all-materials:
    role: "arn:aws:iam::178233312549:role/LabRole"
    handler: src/CRUD_lambda/get-all-materials-painters.handler
    events:
      - httpApi:
          path: /materials
          method: get
  get-all-paints:
    role: "arn:aws:iam::178233312549:role/LabRole"
    handler: src/CRUD_lambda/get-all-paints-painters.handler
    events:
      - httpApi:
          path: /paints
          method: get
  post-materials:
    role: "arn:aws:iam::178233312549:role/LabRole"
    handler: src/CRUD_lambda/post-materials-painters.handler
    events:
      - httpApi:
          path: /materials
          method: post
  post-paints:
    role: "arn:aws:iam::178233312549:role/LabRole"
    handler: src/CRUD_lambda/post-paints-painters.handler
    events:
      - httpApi:
          path: /paints
          method: post
  get-materials-StarWithName:
    role: "arn:aws:iam::178233312549:role/LabRole"
    handler: src/CRUD_lambda/get-materials-StarWithName-painters.handler
    events:
      - httpApi:
          path: /materials/filter/{expression}
          method: get
  get-paints-StarWithName:
    role: "arn:aws:iam::178233312549:role/LabRole"
    handler: src/CRUD_lambda/get-paints-StarWithName-painters.handler
    events:
      - httpApi:
          path: /paints/filter/{expression}
          method: get
  delete-one-materials:
    role: "arn:aws:iam::178233312549:role/LabRole"
    handler: src/CRUD_lambda/delete-one-materials-painters.handler
    events:
      - httpApi:
          path: /materials/{id}
          method: delete
  delete-one-paints:
    role: "arn:aws:iam::178233312549:role/LabRole"
    handler: src/CRUD_lambda/delete-one-paints-painters.handler
    events:
      - httpApi:
          path: /paints/{id}
          method: delete
  get-one-materials:
    role: "arn:aws:iam::178233312549:role/LabRole"
    handler: src/CRUD_lambda/get-one-materials-painters.handler
    events:
      - httpApi:
          path: /materials/{id}
          method: get
  get-one-paints:
    role: "arn:aws:iam::178233312549:role/LabRole"
    handler: src/CRUD_lambda/get-one-paints-painters.handler
    events:
      - httpApi:
          path: /paints/{id}
          method: get
  put-one-materials:
    role: "arn:aws:iam::178233312549:role/LabRole"
    handler: src/CRUD_lambda/put-one-materials-painters.handler
    events:
      - httpApi:
          path: /materials/{id}
          method: put
  put-one-paints:
    role: "arn:aws:iam::178233312549:role/LabRole"
    handler: src/CRUD_lambda/put-one-paints-painters.handler
    events:
      - httpApi:
          path: /paints/{id}
          method: put

resources:
  Resources:
    materials:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: materials
        AttributeDefinitions:
          - AttributeName: element
            AttributeType: S
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: element
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    paints:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: paints
        AttributeDefinitions:
          - AttributeName: element
            AttributeType: S
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: element
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1